#!/usr/bin/env bash

export SERVER_PORT=9085
export LOGGING_LEVEL_COM_GIRAONE=INFO
export SPRING_APPLICATION_NAME=dedup
export SPRING_PROFILES_ACTIVE=loki
export APPLICATION_LOKI_HOST=localhost
export APPLICATION_LOKI_PORT=3100
export APPLICATION_MODE=${1:-PipeDedup}
export APPLICATION_CONSUMER_GROUP_ID=${2:-dedup-default}
export APPLICATION_TOPIC_A=${3:-a1}
export APPLICATION_TOPIC_B=${4:-b1}

# Sample only
# export APPLICATION_CONSUMER_MAX_POLL_INTERVAL=PT300S
# export APPLICATION_CONSUMER_MAX_POLL_RECORDS=100

java -jar target/reactor-kafka.jar
