#!/usr/bin/env bash

export SERVER_PORT=9081
export LOGGING_LEVEL_COM_GIRAONE=INFO
export SPRING_APPLICATION_NAME=produce
export SPRING_PROFILES_ACTIVE=loki
export APPLICATION_LOKI_HOST=localhost
export APPLICATION_LOKI_PORT=3100
export APPLICATION_MODE=${1:-ProduceFlatMapService}
export APPLICATION_TOPIC_A=${2:-a1}
export APPLICATION_PRODUCE_INTERVAL=${3:-1ms}
export APPLICATION_PRODUCER_VARIABLES_MAX_NUMBER_OF_EVENTS=${4:-100000}
export APPLICATION_PRODUCER_VARIABLES_DUPLICATE_PERCENTAGE=${5:-1.0}

java -jar target/reactor-kafka.jar
